Repository lfvilella/pydantic2graphene, pull requests merged in 2021-03, with the labels that each got.

#27 fix flake8
  pydantic2graphene/converter.py
  tests/conftest.py
  tests/fields/test_fields.py
Labels: enhancement

#30 Adding support for nested InputObjectType and type subclasses
  pydantic2graphene/converter.py
  pydantic2graphene/fields.py
  tests/conftest.py
  tests/converter_helper/test_complex_conversions.py
  tests/fields/test_boolean.py
  tests/fields/test_fields.py
  tests/fields/test_float.py
  tests/fields/test_int.py
  tests/fields/test_string.py
Labels: bug, enhancement

#32 update gh actions
  .github/workflows/CI.yml
  .github/workflows/forwards-compatibility.yml
  README.md
Labels: enhancement

#34 release/v0.4
  docs/examples/fastapi_graphql_and_rest/requirements.txt
  docs/examples/fastapi_sqlalchemy/requirements.txt
  pydantic2graphene/version.py
  requirements.txt
  setup.py
Labels: release

#35 update to "Development Status :: 5 - Production/Stable"
  setup.py
Labels: release
